### ISSUE TITLE
node-v0: thrown at `Symbol.iterator in String`

### ISSUE THREAD

**Issue by 59naga** [studio-b12/array-from#8]
``` bash
nvm use 4 && node -e "console.log(require('./')('a'))"
# Now using node v4.1.2 (npm v3.3.12)
# [ 'a' ]

nvm use 0 && node -e "console.log(require('./')('a'))"
# Now using node v0.12.13 (npm v2.15.0)
# /Users/59naga/Downloads/array-from/polyfill.js:20
# ol !== 'undefined') && ('iterator' in Symbol) && (Symbol.iterator in value)) {
#                                                                      ^
# TypeError: Cannot use 'in' operator to search for 'Symbol(Symbol.iterator)' in a
#     at module.exports.iteratorProp (/Users/59naga/Downloads/array-from/polyfill.js:20:92)
#     at from (/Users/59naga/Downloads/array-from/polyfill.js:90:42)
#     at [eval]:1:26
#     at Object.exports.runInThisContext (vm.js:74:17)
#     at Object.<anonymous> ([eval]-wrapper:6:22)
#     at Module._compile (module.js:460:26)
#     at evalScript (node.js:431:25)
#     at startup (node.js:90:7)
#     at node.js:814:3
```

however, the current test will pass normally ...

``` bash
nvm use 0 && npm test
# Now using node v0.12.13 (npm v2.15.0)
# 
#   total:     23
#   passing:   23
#   duration:  61ms
# 
#   All tests pass!
```

**Comment by tomekwi** [comment]
Wow, this changes a great deal

**Comment by tomekwi** [comment]
Hi @59naga, thanks a lot for your contribution! Wonderful work! Please have a look at my two little notes and let me know what you think. Cheers!

By the way, sorry for my previous comment – it was a mistake.
